### ISSUE TITLE
instaloader.exceptions.LoginRequiredException: --login required to get a profile's followers.

### ISSUE THREAD

**Issue by romanrsr** [new92/IGFI#39]
![image](https://github.com/new92/IGFollowersIncreaser/assets/36116699/ae161ca0-d716-4d1b-a0ae-63c274b7de8c)

**Comment by new92** [comment]
Hey @romanrsr, well the error you're encountering basically indicates that in order for the script to provide additional info you have to login to your Instagram account from a webbrowser (Firefox preferably).

**Comment by romanrsr** [comment]
> Hey @romanrsr, well the error you're encountering basically indicates that in order for the script to provide additional info you have to login to your Instagram account from a webbrowser (Firefox preferably).

Hey @new92,

**Comment by new92** [comment]
Yeah sure ! Okay so if the account is new you should be getting this error message. By the way in the installation process did you run the python script (the cookies.py) ? If no it may be due to that. I can't actually think of other reason to cause this error. Try executing again the cookies.py if you have and try again. If the error persists please contact me again !👍

**Comment by new92** [comment]
@romanrsr because another user is encountering the same error it's a bug in the installation process so let me fix it and I'll get back to you.

**Comment by new92** [comment]
@romanrsr I made some changes in the login process please make a `git pull` and execute the script again. If you get any error please contact me again. If everything work fine please mark this issue as closed or contact me to close it. 👍

**Comment by romanrsr** [comment]
Hi @new92, I have done the git pull, I have been able to execute cookies.py correctly, but when I run the V3 script, it keeps telling me "User not found".

**Comment by new92** [comment]
Hey @romanrsr let me try finding a solution to this bug and I'll get back to you asap.

**Comment by new92** [comment]
@romanrsr can you share a screenshot with the error message you're getting ? In order to help you solve this issue. If you don't want to share it on Github you can send it via [email](mailto:new92github@gmail.com)

**Comment by gabyx223** [comment]
ive got a problem,when i try to run the script and get to the follwing question: "Do you consent that the author....etc" i say yes and then the script just closes,any help?

**Comment by new92** [comment]
@gabyx223 are you using the V3 script ? Also do you see a file named: 'cons.txt' appear when entering 'yes' ?

**Comment by gabyx223** [comment]
Fixed that,now it just closes whenever i answer the following question: " Do you grant acces to the script to have acces to the number of followers in order to provide additional information?
I answer with yes and then it just closes
![image_2023-10-28_204816053](https://github.com/new92/IGFI/assets/149209710/2f059cb0-d4f5-4b04-9cc7-498730631369)

**Comment by new92** [comment]
Ok let me fix it and I'll come back to you.

**Comment by gabyx223** [comment]
lar,lmk

**Comment by new92** [comment]
@gabyx223 I made some changes try now maybe it's fixed ?

**Comment by new92** [comment]
@gabyx223 @romanrsr were you able to resolve the issue ?
