### ISSUE TITLE
No Firefox cookies.sqlite file found

### ISSUE THREAD

**Issue by hk493** [new92/IGFI#61]
(igfi) C:\Users\hoto\IGFI>python3 cookies.py
No Firefox cookies.sqlite file found. Use -c COOKIEFILE.

(igfi) C:\Users\hoto\IGFI>python3 cookies.py -c /path/to/your/cookies.sqlite
Using cookies from /path/to/your/cookies.sqlite.
Cookie import failed: unable to open database file

(igfi) C:\Users\hoto\IGFI>python3 cookies.py -c C:\Users\YourUsername\AppData\Roaming\Mozilla\Firefox\Profiles\YourProfileName\cookies.sqlite
Using cookies from C:\Users\YourUsername\AppData\Roaming\Mozilla\Firefox\Profiles\YourProfileName\cookies.sqlite.
Cookie import failed: unable to open database file

(I did from the first step in windows and I'm not sure why its happening, what do i do?

**Comment by new92** [comment]
Hey @hk493 are you connected to your Instagram account from Firefox ?

**Comment by hk493** [comment]
yes i did, do you know any other reasons why it fails?

**Comment by hk493** [comment]
What do i put on the 4th step (path to session file)? I put my username and password for mine and i didnt know what to put on the 4th step.

other than that. Ive logged into my instagram profiles and the 3rd step shows there is no cookie.py file even i downloaded it . please give me any ideas if you have.

**Comment by new92** [comment]
@hk493 to answer your first question, yes there are several other reasons but the main and most common one is that the user is not logged in. But since you are, that's not it. Make sure that you didn't change the default installation path of Firefox and you're using an OS which is supported by IGFI (i.e. Windows, Linux, MacOS). Now, to answer your second question, you replace the <path_to_session_file> with the path generated from the `cookies.py` script. Can you provide me with a screenshot to better understand the error you're facing ? If you're encountering the FileNotFound error then you have to ensure that the `cookies.py` script is in the same directory with IGFI. **Important:** Don't download the files manually, instead follow [the installation guide](https://github.com/new92/IGFI?tab=readme-ov-file#installation-).
